#!/usr/bin/env python3

import asyncio
from datetime import datetime
import websockets

from src.senders import Sender
from src.io_process import stringing, Usage

async def main():
    """
    Loading function. Connect websocket then launch bot.
    """
    async with websockets.connect('ws://sim.smogon.com:8000/showdown/websocket') as websocket:
        Sender(websocket)
        while True:
            message = await websocket.recv()
            print(f'[{datetime.now().replace(microsecond=0).isoformat()}] << {message}')
            await stringing(message, Usage.CHALL_OWNER)


def test():
    """
    Sandbox
    """
    # from src.pokemon import Pokemon

    # pkm1 = Pokemon('Pikachu', 'Pikachu-Kalos', '100/100', True, '92')
    # pkm1.load_unknown()
    # print(pkm1)


if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        loop.run_until_complete(main())
    finally:
        loop.close()
        asyncio.set_event_loop(None)
    # test()
